### ISSUE TITLE
Error Mensage

### ISSUE THREAD

**Issue by golifter** [timersys/popups#5]
Hello,
I'm facing this error after instalation:

Warning: session_start() [function.session-start]: open(/var/lib/php-cgi/session/sess_nbshgjbqcvv5s0puc4eq596o00, O_RDWR) failed: No such file or directory (2) in /home/storage/8/a6/0f/habitusbrasil1/public_html/wp-content/plugins/popups-master/public/includes/class-spu-rules.php on line 10

Can you hep me?

Thank you

**Comment by timersys** [comment]
Looks like something you should talk with your hosting. Seems that session directory is not writable. Maybe this can throw some light http://stackoverflow.com/questions/3262727/warning-session-start-failed-no-such-file-or-directory
