### ISSUE TITLE
PHP Session are started but are not used and prevent caching using Varnish

### ISSUE THREAD

**Issue by tristanleboss** [timersys/popups#7]
Hello,

Your plugin do a "session_start" at line 9 in file "popups\public\includes\class-spu-rules.php".

Strangely, the plugin never uses the session system (no access to global $_SESSION or any other "session_*" functions).

The problem is that PHP session system use a cookie (PHPSESSID, by default) to propagate the session between pages. This cookie prevent caching system like Varnish from working correctly has it induces the delivered content may have been customised for a specific user/session.

Wordpress and most plugins don't use PHP session system.

It would be cool to either 1) delete the call to session_start or 2) add an option to enable/disable use of PHP session system.

**Comment by timersys** [comment]
Hey thanks, if you check the dev branch it's already removed. Was something used on pro version that I left behind by mistake.
Im packing the new version to be released today.

**Comment by tristanleboss** [comment]
Thanks ;)

**Comment by drzraf** [comment]
The 1.9.1 -pro version still create needless cookie.

**Comment by drzraf** [comment]
ping/reopen?
